### ISSUE TITLE
Update for latest available firmwares

### ISSUE THREAD

**Issue by short4bmoney** [nathanfiscus/inovelli-switch-toolbox#2]
My LZW30-SN on/off switch (red series) is on firmware `v1.22` which looks like it breaks out notifications into multiple partial parameters for the relevant arguments. I was able to update the script for my needs, but would love to see the newest firmwares supported in the toolbox web app.

```yaml
alias: Inovelli LED New Firmware
icon: mdi:led-strip-variant
mode: parallel
fields:
  entity_id:
    description: The Inovelli switch entity to target.
    example: light.office_switch
    selector:
      entity:
        filter:
          - integration: zwave_js
  model:
    description: "Device type: dimmer, switch, combo_light"
    example: switch
    selector:
      select:
        options:
          - dimmer
          - switch
          - combo_light
    default: switch
  color:
    description: Choose a color for the notification.
    example: Purple
    selector:
      select:
        options:
          - "Off"
          - Red
          - Orange
          - Yellow
          - Green
          - Cyan
          - Blue
          - Purple
    default: Yellow
  level:
    description: Brightness level of the LED (1-10).
    example: 8
    selector:
      number:
        min: 1
        max: 10
        step: 1
    default: 8
  duration:
    description: How long the notification effect should run.
    example: 5 Minutes
    selector:
      select:
        options:
          - 5 Seconds
          - 30 Seconds
          - 2 Minutes
          - 5 Minutes
          - 20 Minutes
          - 1 Hour
          - Indefinitely
    default: Indefinitely
  effect:
    description: "Choose a visual effect. Note: 'Chase' is for dimmers only."
    example: Blink
    selector:
      select:
        options:
          - "Off"
          - Solid
          - Chase
          - Fast Blink
          - Slow Blink
          - Blink
          - Pulse
          - Breath
    default: Blink
variables:
  model_type: |
    {% if model is string %}
      {{ model }}
    {% elif state_attr(entity_id, 'product_name') is string %}
      {% if 'LZW31' in state_attr(entity_id, 'product_name') %}
        dimmer
      {% elif 'LZW36' in state_attr(entity_id, 'product_name') %}
        combo_light
      {% else %}
        switch
      {% endif %}
    {% else %}
      dimmer
    {% endif %}
  parameters:
    dimmer: 16
    combo_light: 24
    combo_fan: 25
    switch: 8
  colors:
    "Off": 0
    Red: 1
    Orange: 21
    Yellow: 42
    Green: 85
    Cyan: 127
    Blue: 170
    Purple: 195
  durations:
    5 Seconds: 5
    30 Seconds: 30
    2 Minutes: 62
    5 Minutes: 65
    20 Minutes: 80
    1 Hour: 120
    Indefinitely: 255
  effects_dimmer:
    "Off": 0
    Solid: 1
    Chase: 2
    Fast Blink: 3
    Slow Blink: 4
    Blink: 4
    Pulse: 5
    Breath: 5
  effects_switch:
    "Off": 0
    Solid: 1
    Fast Blink: 2
    Slow Blink: 3
    Blink: 3
    Pulse: 4
    Breath: 4
sequence:
  - variables:
      parameter_to_set: "{{ parameters[model_type|lower] }}"
      color_val: "{{ colors.get(color|title, 0) }}"
      duration_val: "{{ durations.get(duration|title, 255) }}"
      effect_val: |
        {% if model_type == "switch" %}
          {{- effects_switch.get(effect|title, 0) }}
        {%- else %}
          {{- effects_dimmer.get(effect|title, 0) }}
        {% endif %}
  - target:
      entity_id: "{{ entity_id }}"
    data:
      parameter: "{{ parameter_to_set }}"
      value: |
        {% if effect_val|int(0) == 0 or color|title == 'Off' %}
          {
            "2130706432": 0
          }
        {% else %}
          {
            "255": {{ color_val }},
            "65280": {{ level|int }},
            "16711680": {{ duration_val }},
            "2130706432": {{ effect_val }}
          }
        {% endif %}
    action: zwave_js.bulk_set_partial_config_parameters
```
